baseURL: "https://parinamais.github.io//parinamais.github.io"
#baseURL: ""
languageCode: en-us
Title: "ParinaMais"
theme: PaperMod
description: My gamedev blog! Here you'll find devlogs and notes on whatever technique I'm currently learning!

params:
  cover:
    linkFullImages: true
  contentWidth: 800px
  padding: 1.5rem
  homeInfoParams:
    Title: Hi!
    Content:  |
      I'm Marina Pais, a brazilian 3D & Tech Artist currently graduating in Computer Science.
      
      My main goal with this blog is to share what I know, but also to learn and improve.
       
      So if you ever have anything to add or correct, please reach out through any of my socials!

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/parinamais/"
    - name: bluesky
      url: "https://bsky.app/profile/parinamais.bsky.social"
    - name: instagram
      url: "https://www.instagram.com/parinamais/"
    - name: itchio
      url: "https://parinamais.itch.io/"
    - name: x
      url: "https://x.com/parinamais"
    - name: github
      url: "https://github.com/parinaMais"
    - name: artstation
      url: "https://www.artstation.com/parinamais"

  ShowBreadCrumbs: true
  #ShowReadingTime: true
  ShowCodeCopyButtons: true
  #ShareButtons: true

  customCSS: ["css/extended/custom.css"]

caches:
  images:
    dir: :cacheDir/images

module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: assets

googleAnalytics: 
  "G-YN51CHFM1Z"
